export const PAGES = {
    HOME: "Home",
    SPLASH: "Splash",
    LOGIN: "Login",
    DRAWER: "Drawer",
    REGISTER: "Register",
    PATIENT_REGISTER: "Patient Register",
    HOSPITAL_REGISTER: "Hospital Register",
    DOCTOR_REGISTER: "Doctor Register",
    LABS_SCAN_REGISTER: "Labs Scan Register",
    DASHBOARD: "Dashboard",
    PATIENT_DASHBOARD:"Patient Dashboard",
    PATIENT_SETTINGS:"Patient Settings",
    PATIENT_HEALTHCARD:"Health Card",
    PATIENT_APPOINTMENTS:"Appointments",
} as const;