import PatientDashboardView from "../screens/AllDashboards/PtDashboard/Overview/PatientDashboardView";

export const PAGES = {
    HOME: "Home",
    SPLASH: "Splash",
    LOGIN: "Login",
    DRAWER: "Drawer",
    REGISTER: "Register",
    PATIENT_REGISTER: "Patient Register",
    HOSPITAL_REGISTER: "Hospital Register",
    DOCTOR_REGISTER: "Doctor Register",
    LABS_SCAN_REGISTER: "Labs Scan Register",
    DASHBOARD: "Dashboard",
    PATIENT_DASHBOARD:"Patient Dashboard",
    PATIENT_SETTINGS:"Patient Settings",
    PATIENT_HEALTHCARD:"Health Card",
    PATIENT_APPOINTMENTS:"Appointments",
    PATIENT_OVERVIEW:"PatientDashboardView",
    LAB_BOOKING:"LabBookingView",
    AMBULANCE_BOOKING_VIEW:"AmbulanceBookingView",
    PHARMACY_FINDER_VIEW:"PharmacyFinderView",
    NOTIFICATION_SCREEN:"NotificationsScreen",
    BOOKING_APPOITMENT:"BookAppoitment",
    BILLING:"Billing",

    // Lab Page
  LAB_HOME: "LabHome",
  LAB_CART: "LabCart",
  LAB_DETAILS_PAGE: "LabDetails",
  AVAILABLE_LABS: "AvailableLabs",
  LAB_BOOKING_PAGE: "LabBooking",
  LAB_BOOK_APPOINTMENT: "LabBookAppointment",
  LAB_PAYMENT: "LabPayment",
  LAB_PAYMENT_SUCCESS: "LabPaymentSuccess",
  LAB_TRACK_APPOINTMENT: "LabTrackAppointment",
} as const;