export const PAGES = {
    HOME: "Home",
    SPLASH: "Splash",
    LOGIN: "Login",
    DRAWER: "Drawer",
    REGISTER: "Register",
    PATIENT_REGISTER: "PatientRegister",
    HOSPITAL_REGISTER: "HospitalRegister",
    DOCTOR_REGISTER: "DoctorRegister",
    LABS_SCAN_REGISTER: "LabsScanRegister",
    DASHBOARD: "Dashboard",
    PATIENT_DASHBOARD:"PatientDashboard",
    PATIENT_SETTINGS:"PatientSettings",
    PATIENT_HEALTHCARD:"Health Card",
    PATIENT_APPOINTMENTS:"Appointments",
} as const;